production:
  sms_wsdl: http://211.157.113.148:8060/webservice.asmx?WSDL
  sms_sn: SDK-SKY-010-00281
  sms_pwd: 092395

development:
  sms_wsdl: http://211.157.113.148:8060/webservice.asmx?WSDL
  sms_sn: SDK-SKY-010-00281
  sms_pwd: 092395

test:
